version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.4.0

jobs:

  build:
    docker: 
      - image: python:3.7.3-stretch
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make setup
            make install
            pip3 install pylint
            pylint --help
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
            
################################# BUILDING PHASE #################################

  build-docker-image:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build --tag=capstone .
            docker image ls
      - run:
          name: Push Docker image into Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            dockerpath=v4ldus/capstone
            docker tag capstone $dockerpath
            echo "Docker ID and Image: $dockerpath"
            docker push $dockerpath
            
            
            
            
#################################    Workflow    #################################

workflows:
    default:
        jobs:
          - lint
          - build-docker-image:
              requires: [lint]